import Head from 'next/head';
import { Inter } from '@next/font/google';
import { Canvas } from '@react-three/fiber';
import Box from '@/components/Box';
import Plane from '@/components/Plane';
import { Environment, OrbitControls, ScrollControls } from '@react-three/drei';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Canvas
          shadows='soft'
          style={{ position: 'absolute', height: '100vh' }}
          camera={{ fov: 75, near: 0.1, far: 1000, position: [0, 3, 5] }}
        >
          <Environment files='kloppenheim_06_puresky_2k.hdr' background />
          <directionalLight castShadow position={[20, 20, 20]} />
          <ambientLight intensity={0.3} />
          <pointLight position={[10, 10, 10]} />
          <ScrollControls pages={3} damping={0.1}>
            <Box castShadow position={[-1.2, 1, 0]} rotation={[0, 2, 1]} />
            <Box castShadow position={[1.2, 1, 0]} />
          </ScrollControls>
          {/* <Plane
            receiveShadow
            position={[0, 0, 0]}
            rotation={[Math.PI / -2, 0, 0]}
          /> */}
        </Canvas>
      </main>
    </>
  );
}
