import Head from 'next/head';
import { Inter } from '@next/font/google';
import { Canvas } from '@react-three/fiber';
import Box from '@/components/Box';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Canvas style={{ position: 'absolute', height: '100vh' }}>
          <ambientLight />
          <pointLight position={[10, 10, 10]} />
          <Box position={[-1.2, 0, 0]} rotation={[0, 2, 1]} />
          <Box position={[1.2, 0, 0]} />
        </Canvas>
      </main>
    </>
  );
}
